### ISSUE TITLE
Unable to start - Error: Cannot find module 'highcharts/highcharts.js' and other

### ISSUE THREAD

**Issue by debiprasad** [start-angular/ani-angular-2#8]
I am unable to start. When I try to start using `npm start`, I see the following errors:

```
[13:20:17] 'build.html_css' errored after 8.26 s
[13:20:17] Error: Cannot find module 'highcharts/highcharts.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.require.resolve (internal/module.js:23:19) ...
```

**Comment by aniramirez2** [comment]
how did you resolve this?

**Comment by oitejjho** [comment]
due to highchart node module dependency is missing. Try to install hightchart using npm locally(in your project directory)/globally
npm install highcharts
npm install -g highcharts
